### ISSUE TITLE
res2 not defined

### ISSUE THREAD

**Issue by Jay-Joshi-Axel** [parvatijay2901/Automatic-Number-plate-detection-for-Indian-vehicles#2]
Traceback (most recent call last):
  File "/home/pi/Desktop/ANPR/Program.py", line 178, in <module>
    print("The car number to search is:- ",res2)
NameError: name 'res2' is not defined

**Comment by parvatijay2901** [comment]
Was the issue in the entered image directory? @Jay-Joshi-Axel

**Comment by Jay-Joshi-Axel** [comment]
1) This error was occuring because i was not giving the directory path properly.
After giving path properly another error occured which i have mentioned below


2)No issue was not in image directory, issue was in a line of code but i got
the solution on stackoverflow
if you want to check the issue -
https://stackoverflow.com/questions/25504964/opencv-python-valueerror-too-many-values-to-unpack
Thanks for your code and work.

**Comment by malfoy001** [comment]
Traceback (most recent call last):
File "/home/pi/Desktop/ANPR/Program.py", line 178, in
print("The car number to search is:- ",res2)
NameError: name 'res2' is not defined

**Comment by trilokdhaked** [comment]
Traceback (most recent call last):
  File "/Users/trilokdhaked/Downloads/Automatic-Number-plate-detection-for-Indian-vehicles-main/Program.py", line 177, in <module>
    print("The car number to search is:- ",res2)
NameError: name 'res2' is not defined

-------Please  tell solution this   error

**Comment by Jay-Joshi-Axel** [comment]
Please check my above comment, In that I have given the link for the solution.

**Comment by trilokdhaked** [comment]
> Please check my above comment, In that I have given the link for the solution.

i am not understand please  tell me properly

**Comment by UsarthiAruna** [comment]
> Traceback (most recent call last): File "/Users/trilokdhaked/Downloads/Automatic-Number-plate-detection-for-Indian-vehicles-main/Program.py", line 177, in print("The car number to search is:- ",res2) NameError: name 'res2' is not defined
> 
> -------Please tell solution this error

Just give tab space before that line

**Comment by UsarthiAruna** [comment]
Traceback (most recent call last):
File "c:\anpr\Automatic-Number-plate-detection-for-Indian-vehicles-main\Program.py", line 154, in
res2 = str("".join(re.split("[^a-zA-Z0-9]*",number_plate)))
File "C:\Python310\lib\re.py", line 230, in split
return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object

Anyone Please tell me how to solve this error

**Comment by parvatijay2901** [comment]
Check https://github.com/parvatijay2901/Automatic-Number-plate-detection-for-Indian-vehicles/issues/2#issuecomment-793467531

**Comment by Tusharroy01** [comment]
res2 is not defined. Can you please explain me in a detailed way how to solve this?
