### ISSUE TITLE
After giving paths of folders i am seeing this 2 errors

### ISSUE THREAD

**Issue by Jay-Joshi-Axel** [parvatijay2901/Automatic-Number-plate-detection-for-Indian-vehicles#3]
Traceback (most recent call last):
  File "/home/pi/Desktop/ANPR/Program.py", line 157, in <module>
    number_plate=number_plate_detection(img)
  File "/home/pi/Desktop/ANPR/Program.py", line 84, in number_plate_detection
    num_contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack (expected 2)

**Comment by Jay-Joshi-Axel** [comment]
just add a '_' before 'num_contours' because you are not using the required var 
Dont forget to separate it by a ',' 

otherwise copy this line and replace it in code wherever necessary - _ , num_contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)


Answer reference - https://stackoverflow.com/questions/25504964/opencv-python-valueerror-too-many-values-to-unpack

**Comment by UsarthiAruna** [comment]
Traceback (most recent call last):
File "c:\anpr\Automatic-Number-plate-detection-for-Indian-vehicles-main\Program.py", line 154, in
res2 = str("".join(re.split("[^a-zA-Z0-9]*",number_plate)))
File "C:\Python310\lib\re.py", line 230, in split
return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object

**Please tell me how to solve this error**
